### ISSUE TITLE
init

### ISSUE THREAD

**Issue by landsman** [CSHH/git-branch-panel#1]
Hi,

how can i set my entryPath? 
how can i install via composer?

thanks

**Comment by lukasneubauer** [comment]
Hi,

I have updated readme with installation info `composer require --dev heavenproject/git-branch-panel`

and I see it would be a good idea to set the entryPath as configurable option via neon configuration, so I will make i so.

Thanks :)

**Comment by lukasneubauer** [comment]
It´s done. I have just released new version https://github.com/CSHH/git-branch-panel/releases/tag/v1.1.0.
